site_name: transformer-agents
repo_url: https://github.com/dtch1997/transformer-agents
site_url: https://dtch1997.github.io/transformer-agents
site_description: Experiments with HuggingFace Trmer Agents
site_author: Daniel C.H. Tan
edit_uri: edit/main/docs/
repo_name: dtch1997/transformer-agents
copyright: Maintained by <a href="https://dtch1997.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dtch1997/transformer-agents
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/transformer-agents

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true